services:
  back-taskmanager:
    image: shaqteam/shaq-back
    command: sh -c "yarn run build && yarn run prod"
    ports:
      - 5050:4000
    depends_on:
      - mongodb

  front-taskmanager:
    image: shaqteam/shaq-front
    command: sh -c "yarn build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:4.4

  nginx:
    image: nginx:1.21.3
    depends_on:
      - back-taskmanager
      - front-taskmanager
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
