name: jest-ci

on: 
  push:
    branches-ignore: 
      - "master"

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      -
      name: Check out code 
      uses: actions/checkout@v2
      -
      name: Go to app and run tests
      run: cd app && yarn && yarn test