name: ci-production

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch webhook
        run: curl https://ops.paris1-0921.wns.wilders.dev/hooks/update-prod
